import { FaGithub } from "react-icons/fa";
import { FiZap, FiBookOpen, FiArrowRight, FiPlusCircle } from "react-icons/fi";

export const featureCards = [
  {
    icon: FaGithub,
    bg: "#DBEAFE",
    title: "Compatible with All Public GitHub Repos",
    desc: "Connect and generate documentation for any public repository with ease.",
  },
  {
    icon: FiZap,
    bg: "#fff7ed",
    title: "Lightning-Fast README Generation",
    desc: "Get professional documentation in seconds using advanced AI technology.",
  },
  {
    icon: FiBookOpen,
    bg: "#eefaf1",
    title: "Full Documentation Coming",
    desc: "Complete code documentation features are in development and coming to you soon.",
  },
];

export const roadmapPhases = [
  {
    title: "Phase 1: README Generation",
    desc: "Available now – Create professional README files instantly.",
  },
  {
    title: "Phase 2: Full Code Documentation",
    desc: "Available now – Comprehensive documentation for classes, functions, and more.",
  },
  {
    title: "Phase 3: Apply & Download",
    desc: "Available now – Apply automatic and Download files instantly.",
  },
  {
    title: "Phase 4: Repositories Types",
    desc: "Available now – Access Private and Public Repo With User Permission.",
  },
  {
    title: "Phase 5: README Update Time",
    desc: "Coming Soon – After update Projects Repo Then Check whole Projects new functionality and Update Readme file.",
  },
];

export const faqList = [
  {
    question: "How can Readme Hub improve my GitHub profile to attract recruiters and boost my career?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
  {
    question: "How long does it take to generate a high-quality README with Readme Hub?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
  {
    question: "Is my code protected and secure when using Readme Hub?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
  {
    question: "Can I customize the layout and style of my README generated by Readme Hub?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
  {
    question: "Which programming languages does Readme Hub support?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
  {
    question: "How does Readme Hub’s AI analyze and review my code to create documentation?",
    answer: "Demo answer text for this question. You can replace this with your actual answer.",
  },
];

export const bottomCTA = {
  icon: FiPlusCircle,
  text: "Can’t find what you’re looking for?",
  linkText: "Contact us",
  link: "mailto:contact@readmehub.example",
};